
require('./variables/property')
require('./variables/count')
require('./variables/aggregate')
require('./variables/typeset')
require('./variables/one')

require('./variables/time')
require('./variables/map')
require('./variables/multimap')
require('./variables/top')
require('./variables/switch')
require('./variables/type')
require('./variables/filter')
require('./variables/each')
require('./variables/eachReduce')
require('./variables/subset')
require('./variables/traverse')
require('./variables/sessions')
require('./variables/versions')
require('./variables/lastVersion')
require('./variables/timestamps')
require('./variables/timestamp')
require('./variables/isOfType')
require('./variables/preforked')
require('./variables/mutate')

